truncate table
  public.analysis_job_messages,
  public.model_runs,
  public.analysis_jobs,
  public.automation_decisions,
  public.wa_sync_runs,
  public.automation_settings,
  public.whatsapp_agent_contact_memories,
  public.whatsapp_agent_messages,
  public.whatsapp_agent_thread_sessions,
  public.whatsapp_agent_threads,
  public.whatsapp_agent_settings,
  public.chat_messages,
  public.chat_threads,
  public.important_messages,
  public.person_memory_snapshots,
  public.person_memories,
  public.project_memories,
  public.memory_snapshots,
  public.persona,
  public.whatsapp_known_contacts,
  public.whatsapp_known_groups,
  public.message_retention_state,
  public.processed_message_ids,
  public.mensagens,
  public.wa_session_keys,
  public.wa_sessions
restart identity cascade;
